### ISSUE TITLE
Refus d'installer avec Kodi 16.1

### ISSUE THREAD

**Issue by mathieugouin** [service-paradis/plugin.tva.videos#1]
Salut, je suis encore sur Kodi 16.1.

Est-ce normal que l'installation à partir du zip échoue.  Je reçois le message:

Cannot meet dependency xbmc.python 2.25

Ça te dit quelque chose?

Merci!

**Comment by service-paradis** [comment]
Salut,

J'ai peut-être été un peu trop strict sur les prérequis. Peux-tu essayer de modifier le fichier « addon.xml »?
Modifie la ligne suivante :
     `<import addon="xbmc.python" version="2.25.0"/>`
pour y mettre plutôt :
     `<import addon="xbmc.python" version="2.1.0"/>`

**Comment by mathieugouin** [comment]
C'est bon ça marche maintenant, merci.

**Comment by mathieugouin** [comment]
Je vais essayer de te faire un pull request.

**Comment by service-paradis** [comment]
@mathieugouin 
Veux-tu faire un pull request ou me dire quels changements tu as fait? Je mettrai à jour le GIT.

Merci!

**Comment by mathieugouin** [comment]
Désolé, je n'ai pas eu beaucoup de temps récemment.  J'ai eu à copier l'icon et le fanart au root aussi, parce que kodi 16 à 17 ont changé l'emplacement des fichiers.

Voir: http://kodi.wiki/view/Add-on_structure#Directory_structure

**Comment by mathieugouin** [comment]
Salut j'ai vu que tu as fait le changement dans ton git.  Je close l'issue.  Merci!
